

[pytest]
pythonpath = src
testpaths = tests

# ---------- DEFAULT OPTIONS ----------
addopts =
    -ra
    -q
    --tb=short
    --alluredir=allure-results
    --clean-alluredir

# ---------- TEST MARKERS ----------
markers =
    smoke: critical tests for build verification
    sanity: basic functionality validation
    regression: full regression test suite

# ---------- WARNINGS ----------
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
